### ISSUE TITLE
Is this still being developed?

### ISSUE THREAD

**Issue by oneduality** [mobbyg/anet_bbs#1]
I have an emulated version of CNet Pro 3.05c and stormedged apparently released 5.x but they don't respond to attenpts to contact them.. 

I agree that there should be something like this for PC, it was one of the absolute best.. starting with 3.x might be a good point forward.. not sure where you were starting from but obviously you have a reference point.

**Comment by mobbyg** [comment]
Sorry for the late reply, didn’t get a notification. But actually, I am starting to look at working on this again as some of my Python Skills have improved. But there is still a lot that need to be worked on. I have a beginning GUI and will be working on an internal socket server instead of relying on a telnet replacement.

**Comment by mobbyg** [comment]
Yes.
